### ISSUE TITLE
[login] Whitespace not allowed in character names

### ISSUE THREAD

**Issue by Moria15** [wovencode/OpenMMO#11]
If space entered in Character name,  no character created, system just returns to character setup menu.  0.9c  2019.0.3

**Comment by Moria15** [comment]
Confirmed in 0.9d no spaces allowed..  screen stays..  might be nice to have a warning window pop-up as to why?

**Comment by DX4D** [comment]
(Devs: See issue #3 in the other issue tracker...ignore what got linked here)

**Comment by DX4D** [comment]
I think we can use something like   "**_**"   inside the database and then Trim that out when we pull it back out of the database to solve this issue. While we're at it we might want to trim out any special characters too so we can prevent the possibility of any sort of code injection here.

`string.Replace(" ", "_"); should do nicely to turn spaces to inline data.`

**Comment by DX4D** [comment]
Fixed...plus added profanity filter and disallows whitespace at the beginning or end of a name
