### ISSUE TITLE
Variable naming inconsistencies 

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#13]
While attempting to write some documentation I realized that there were some inconsistencies in variable names. 

For example, sometimes Player is used instead of User and vicer versa. Username vs name. etc. I found myself being confused occasionally while reading the code.
I think it might be a good idea to get rid of these inconsistencies before the project becomes even larger as they could cause some misunderstandings.

Pardon if this is the wrong way of poiting out this issue/reporting this issue as this is the first time im attempting this.

**Comment by wovencode** [comment]
good idea, will happen in a few days

note:

"player" is the "character" you are playing
while "user" is the "account"

im using a different naming convention than most other assets out there

but you are right with things like "name" - it should be "username" or "playername" in that case to make it more clear

**Comment by wovencode** [comment]
Should be fixed on 0.09 f onwards
