### ISSUE TITLE
In-Zone Multi portal multi user error

### ISSUE THREAD

**Issue by Moria15** [wovencode/OpenMMO#15]
In seperate client server build on 0.9d if a character enters the mutli zone portal, a message appears saying portal y/n.  If another character enters the portal, they also get same message..  if either charater then selects yes, the portal y/n message dissapears on both clients, not just the one that portaled meaning the other has to back out of the portal to re-activate it

**Comment by wovencode** [comment]
should be fixed in 0.10

**Comment by Moria15** [comment]
indeed it is.. closing.
