### ISSUE TITLE
NetworkManager - Search & add Prefabs - Not functioning as intended

### ISSUE THREAD

**Issue by DX4D** [wovencode/OpenMMO#17]
When clicking the Search and Add Prefabs button, it appears to work as intended, but when you hit Play it reverts to the original values for spawnPrefabs.

**Comment by DX4D** [comment]
It works as intended if you click the button in the inspector at runtime before logging in. Something is resetting it when hitting play in Host and Play mode

**Comment by wovencode** [comment]
fixed in 0.1.1
