### ISSUE TITLE
[data] SQLite database is overwritten when multiple OpenMMO projects are on the same user account

### ISSUE THREAD

**Issue by Moria15** [wovencode/OpenMMO#19]
OK Unity is now storing, for 2019, the DB in a new place..  AppData\LocalLow\DefaultCompany  however it is supposed to also use the project name  so it should be AppData\LocalLow\DefaultCompany\OpenMMO.      In here are stored the player logs etc..  however on windows, it is ignoring the \OpenMMO  so all databases from all projects listed as default company are being stored in the root of  AppData\LocalLow\DefaultCompany  so if you have more than one project in default Company but with the same Db name (Database.sqlite) then the Db's are overwriting each other.   The name of the Db in Open MMO should be changed to avoid this being an issue.   Recommend OpenMMO.sqlite but be aware if you have 2 projects running currently they will overwrite databases unless one is changed.

**Comment by wovencode** [comment]
Temporarily Hotfixed by changing the name to "DatabaseOpenMMO.sqlite" but that does not solve the issue in general.

**Comment by DX4D** [comment]
Will need to reconfirm this bug, but I believe recent changes such as giving each zone a unique log and putting the logs in a sub folder may have solved this issue for the most part. SQLite is primarily for testing, so even even if the sqlite database is limited to one per user on the server, there are ways to circumnavigate this by running one account per server or run multiple virtual machines.

If this does not apply when using MySQL I think we can safely close this bug and perhaps explain as above in the documentation.

**Comment by DX4D** [comment]
SQLite is meant for testing... Because the above mentioned workarounds can avoid the issue with SQLite and it does not effect MySQL this issue can be closed.
