### ISSUE TITLE
Curl Crashes with unity

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#28]
Not sure if this is even us or just unity being dumb, seems to be a php error? It goes away when you hit clear...have not noticed any obvious side affects
Update: Looks like a Unity issue: https://forum.unity.com/threads/crashes-unity-with-curl-error-56-receiving-data-failed-with-unitytls-error-code-1048578.795066/

![](https://i.imgur.com/kCErDr4.png)

**Comment by DX4D** [comment]
This is a known Unity bug...will likely be fixed with future Unity updates
