### ISSUE TITLE
[UI] Player nameplates display the prefab's name

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#32]
Other clients players are shown as "Human (Clone)" instead of their name. Its ok for the local client and in host+play

**Comment by francy51** [comment]
Name of other characters in zone still say Human/Elf/Dwarf(clone) after them rather than char name.

**Comment by DX4D** [comment]
Player names will need to be synced to all nearby clients to solve this issue. Most likely a SyncVar will be the best solution.

**Comment by wovencode** [comment]
fixed

can be closed after confirmed

**Comment by DX4D** [comment]
Confirmed Fixed
