### ISSUE TITLE
Name tags flipping and Camera positioning issues

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#33]
okay wierd one to describe...   in the attached pic.. the character on the left screen zoned in...  on the screen of the character on the right screen, who hadn't moved, the name tags flipped at the zone in.  They correct themselves as soon as the character in the right screen moves, but it's wierd..  please ask if this is not clear.  It also moves the camera fron behind the current character to looking at the zone in point of the second character.. may be why the names flip because the camera is being overriden on target..  in some cases Camera looses position on zoning character as well

![](https://cdn.discordapp.com/attachments/677473410720464916/677983806749278238/Clone.jpg)

**Comment by DX4D** [comment]
Fixed
