### ISSUE TITLE
[data] blank spaces in file path causing crashes

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#40]
System fails if there are blank spaces in the directory names of the project in Windows..  all directory and project names must have no whitespace in them

**Comment by DX4D** [comment]
(Devs: See issue #20 in the other issue tracker...ignore what gets linked here)

**Comment by wovencode** [comment]
this is more difficult to fix as Start.Process separates the process path and the argument with a "whitespace".

**Comment by DX4D** [comment]
Good progress on this so far, works on Windows and Linux now...just need to figure out the OSX end of things and we can finally close this one down.

**Comment by DX4D** [comment]
Working now in OSX, Linux, and Windows (pending testing)
It should be noted in bold that the server.exe (or equivalent) MUST be named "server" no matter what for additional zone servers to spawn. We can revisit this later on to allow that file to have a different name.

After testing we can close this issue and create a [task] to allow different names for the server.exe in the future.

**Comment by DX4D** [comment]
For Future Reference: (untested)
https://stackoverflow.com/questions/17321289/use-process-start-with-parameters-and-spaces-in-path

**Comment by DX4D** [comment]
Fixed!
