### ISSUE TITLE
editor improvement considerations

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#41]
when host/play selected in network manager..  Active network zones should be unchecked..  likewise if Client or Server selected  should be checked..  to easy to forget  (well for me anyway)

**Comment by francy51** [comment]
If we see this as an issue we can add it as an official task to our todo list. Otherwise this issue will simply be closed.

**Comment by DX4D** [comment]
Fixed with OpenMMO>Change Build Menu
