### ISSUE TITLE
Issue with text overhead of player

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#43]
Issue with text overhead of player,  name,  level  and Zone Information..  each time you zone it lowers it slightly and angles it away from the camera..  after about 8 - 10 zones..  it looks like the starwars intro text

**Comment by DX4D** [comment]
Solution: Create an "AlwaysUp" component that sets the transform.up to Vector3.up periodically.

**Comment by DX4D** [comment]
Fixed
