### ISSUE TITLE
[navmesh] Invisible walls.

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#48]
Could just be the navmesh needing to be rebaked.

**Comment by francy51** [comment]
Invisible wall occuring here.

![image](https://user-images.githubusercontent.com/18003612/74653553-5c770d00-51c3-11ea-88c6-9c2aa113dad6.png)

Another invisible wall located at the bride.

**Comment by wovencode** [comment]
fixed on latest push.
