### ISSUE TITLE
[network] logging too fast causing refused connection

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#50]
when logging in locally using 2+ built clients, one of them always gets its connection refused. only happens when logging in too fast.

**Comment by Moria15** [comment]
This has to be lag or similar..  I tried this with 3 clients today and hit all three logins within half a second of each other and no issues and all three characters loaded fine, so not sure what to suggest,  Will ask others with lower specs to try to repo.

**Comment by wovencode** [comment]
should be fixed
