### ISSUE TITLE
[camera][ui] when logging into a zone ui alignment is incorrect 

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#53]
actually an old one back..  when logging into a zone, if there is a character in that zone, the camera on the character in the zone uses the new character that zoned in as an alignment for the text above their own character leading to misplaced text above existing character in zone.  As soon as existing character is moved, it resets to being correct

**Comment by DX4D** [comment]
Fixed - Main Camera was not being disabled when the player cam was spawned
