### ISSUE TITLE
[camera][ui] text not aligning correctly

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#55]
The text seems to missalign after a while. Not sure what caused this as I was idling on the client which it occurs on.

![image](https://user-images.githubusercontent.com/18003612/74963435-ac1c3980-544c-11ea-83af-1790ec991e93.png)

**Comment by francy51** [comment]
It doesn't fix itself once you move the camera or walk around

**Comment by DX4D** [comment]
fixed...was due to having multiple cameras in the scene
