### ISSUE TITLE
Errors on server start

### ISSUE THREAD

**Issue by CliffBramlett** [wovencode/OpenMMO#72]
Fresh install using /Assets/OpenMMO/Documentation/!! Quickstart Guide !!.txt
Only 2 processes started. Full server text is in [2021-03-27 First start.txt](https://github.com/wovencode/OpenMMO/files/6214677/2021-03-27.First.start.txt)

Was able to register, then log in, but scene appeared unlit
![First login](https://user-images.githubusercontent.com/47966642/112701012-c0243d00-8e8f-11eb-8d7c-a0eedaa51a9c.png)

**Comment by CliffBramlett** [comment]
Note: I read about people taking a break, but I'd like to start working on this project if it isn't going to be dropped completely, hence this bug report.

**Comment by DX4D** [comment]
Need a few more details:
What version is this (Asset Store/Git Repo (dev or release?))

Give this version a try instead:
https://github.com/wovencode/OpenMMO/raw/develop/_STABLE%20RELEASE/OpenMMO_FRAMEWORK%2BEXAMPLE.zip

**Comment by CliffBramlett** [comment]
Unity ver 2019.4.23f1 (LTS), and used GitHub to get the OpenMMO download. Will try that version tomorrow, asap (likely 12-18 hrs from this post)

**Comment by CliffBramlett** [comment]
So much for my timeframe. Life happened. Anyway, I extracted both files to a folder and tried to open them in Unity, but Unity doesn't recognize them as projects. Going to try importing next.

**Comment by CliffBramlett** [comment]
Got several warnings with the Framework import

***** One of this unable to parse *****
Unable to parse file Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Runtime/Transport/Telepathy/Telepathy.dll.meta: [Parser Failure at line 30: Expect ':' between key and value within mapping]

***** 6 of the following error types *****
Mirror.Weaver warning: OpenMMO.GameItem has no public or non-static fields to deserialize
UnityEngine.Debug:LogWarning (object)
Mirror.Weaver.CompilationFinishedHook:HandleWarning (string) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/CompilationFinishedHook.cs:38)
Mirror.Weaver.Log:Warning (string) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/Program.cs:14)
Mirror.Weaver.Readers:GenerateClassOrStructReadFunction (Mono.CecilX.TypeReference,int) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/Readers.cs:386)
Mirror.Weaver.Readers:GetReadFunc (Mono.CecilX.TypeReference,int) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/Readers.cs:81)
Mirror.Weaver.SyncObjectProcessor:GenerateDeserialization (string,Mono.CecilX.TypeDefinition,Mono.CecilX.TypeReference) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs:105)
Mirror.Weaver.SyncObjectProcessor:GenerateSerialization (Mono.CecilX.TypeDefinition,int,string,string) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs:34)
Mirror.Weaver.SyncListProcessor:Process (Mono.CecilX.TypeDefinition) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/Processors/SyncListProcessor.cs:14)
Mirror.Weaver.Weaver:CheckSyncList (Mono.CecilX.TypeDefinition) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/Weaver.cs:424)
Mirror.Weaver.Weaver:Weave (string,System.Collections.Generic.IEnumerable`1<string>,string,string,string) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/Weaver.cs:502)
Mirror.Weaver.Weaver:WeaveAssemblies (System.Collections.Generic.IEnumerable`1<string>,System.Collections.Generic.IEnumerable`1<string>,string,string,string) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/Weaver.cs:575)
Mirror.Weaver.Program:Process (string,string,string,string[],string[],System.Action`1<string>,System.Action`1<string>) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/Program.cs:33)
Mirror.Weaver.CompilationFinishedHook:OnCompilationFinished (string,UnityEditor.Compilation.CompilerMessage[]) (at Assets/Plugins/OpenMMO/Plugins/Extras [3rd Party]/Mirror/Editor/Weaver/CompilationFinishedHook.cs:161)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline (UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget)

****** 1 each of the following *****
File 'Test Model@Walk' has rig import warnings. See Import Messages in Rig Import Tab for more details.

File 'Test Model@Walk' has animation import warnings. See Import Messages in Animation Import Settings for more details.

File 'Test Model@Idle' has rig import warnings. See Import Messages in Rig Import Tab for more details.

File 'Test Model@Idle' has animation import warnings. See Import Messages in Animation Import Settings for more details.


***** Attempting a build (Win64) results in:
NullReferenceException: Object reference not set to an instance of an object
OpenMMO.ChangeBuildMenu.SetBuildType (OpenMMO.Network.NetworkType buildType, System.Boolean headless) (at Assets/Plugins/OpenMMO/Plugins/Addons/EditorSystems/QuickBuildMenus/ChangeBuildMenu.cs:24)
OpenMMO.QuickBuildMenu.Build (UnityEditor.BuildTarget targetPlatform, OpenMMO.Network.NetworkType buildType, System.Boolean headless) (at Assets/Plugins/OpenMMO/Plugins/Addons/EditorSystems/QuickBuildMenus/QuickBuildMenu.cs:58)
OpenMMO.QuickBuildMenu.BuildHeadlessServer (UnityEditor.BuildTarget targetPlatform) (at Assets/Plugins/OpenMMO/Plugins/Addons/EditorSystems/QuickBuildMenus/QuickBuildMenu.cs:170)
OpenMMO.QuickBuildMenu.BuildClientAndHeadlessServer (UnityEditor.BuildTarget targetPlatform) (at Assets/Plugins/OpenMMO/Plugins/Addons/EditorSystems/QuickBuildMenus/QuickBuildMenu.cs:163)
OpenMMO.QuickBuildMenu.BuildWindows64ClientAndHeadlessServer () (at Assets/Plugins/OpenMMO/Plugins/Addons/EditorSystems/QuickBuildMenus/QuickBuildMenu.cs:218)

**Comment by CliffBramlett** [comment]
Doing the same import for the example results in 6 duplicate errors:
******
Identifier uniqueness violation: 'Name:Missing Prefab (Dummy), Type:GameObject'. Multiple Objects with the same name/type are generated by this Importer. There is no guarantee that subsequent imports of this asset will properly re-link to these targets.

**Comment by DX4D** [comment]
Are you using a newer version of mirror, or the version included in the
project? We're still way behind the latest mirror version

**Comment by DX4D** [comment]
Also, what unity version are you using? We built this based on 2019 LTS, so
there could be potential issues with 2020 versions etc

**Comment by CliffBramlett** [comment]
Unity ver 2019.4.23f1 (LTS), see a few posts above  :)
So I should use the latest version of Mirror? I thought it was included in this package. That would explain a lot if not, but it would be weird that the first one started at all if it isn't.

**Comment by DX4D** [comment]
It should be working as-is with the mirror version included in the download. I did run into this same issue with an older version and had to rebuild the scenes from scratch to fix the lighting. Issue is in the scene itself somewhere, not mirror or openmmo afaik. I've still got this injury and can't really use the mouse to rebuild the scenes, but that's where I'd start if this thing ever heals. Let me know if you try it and I'm happy to help however I can manage while typing lefty on my phone 😂

**Comment by DX4D** [comment]
Also, openmmo is not designed to run in the editor, you need to do a full build and run the server to test it properly. Looks like you had it running that way, just wanted to mention it just in case 👍

**Comment by DX4D** [comment]
Just noticed this in your original log files, you will need to add the scenes in your build settings for them to load properly. Should be details in the quickstart on how to do that. 

"Scene 'Login Sub Scene 1' couldn't be loaded because it has not been added to the build settings or the AssetBundle has not been loaded.
To add a scene to the build settings use the menu File->Build Settings...
(Filename:  Line: 170)"

**Comment by CliffBramlett** [comment]
Wow, can't believe I forgot the build settings! Will try that soon.

**Comment by CliffBramlett** [comment]
So I tried the above without success. I also tried dragging in the missing Login Sub Scene 1 from your files into the project that was actually building from this git repository, but that didn't help either. I tried to troubleshoot the problem in graphics, and I *think* it might be an issue with a missing rendering pipeline, but couldn't get it to work. I'm guessing the Unity version difference could also be causing problems. After looking into Mirror a bit more it appears that is where one of the devs here moved to. So I'm going to compare that and see if it serves what uMMORPG was supposed to do.

**Comment by Tumeski** [comment]
> 
> 
> So I tried the above without success. I also tried dragging in the missing Login Sub Scene 1 from your files into the project that was actually building from this git repository, but that didn't help either. I tried to troubleshoot the problem in graphics, and I _think_ it might be an issue with a missing rendering pipeline, but couldn't get it to work. I'm guessing the Unity version difference could also be causing problems. After looking into Mirror a bit more it appears that is where one of the devs here moved to. So I'm going to compare that and see if it serves what uMMORPG was supposed to do.

Im learning some basics here too and learning a lot from this project. I noticed that they have changed the way they deal with login scene and this "Login Sub Scene 1" is depricated info, for some reason it has been "cached" for "Default Login Scene" itself. I simply went to "Default Login Scene" -> Under "Light etc." in Hierarchy you found "AreaPortal". From there Area Portal script uses Sub Scene value. Set it so some scene and then back to none, rebuild and the warning is gone and compiler not trying to find "Login Sub Scene 1" anymore.

**Comment by DX4D** [comment]
Great catch @Tumeski 

I've gone in and removed all those pesky sub-scene links and pushed a fix for all the lighting issues to the "develop" branch on the git repo. The latest version there works with Unity 2020.3 and is updated to Mirror v42 give that a try and see if it has solved the issues you were having before @CliffBramlett 

Closing this issue for now, please reopen or create a new one is the issue still exists with the latest develop branch updates. 

> > So I tried the above without success. I also tried dragging in the missing Login Sub Scene 1 from your files into the project that was actually building from this git repository, but that didn't help either. I tried to troubleshoot the problem in graphics, and I _think_ it might be an issue with a missing rendering pipeline, but couldn't get it to work. I'm guessing the Unity version difference could also be causing problems. After looking into Mirror a bit more it appears that is where one of the devs here moved to. So I'm going to compare that and see if it serves what uMMORPG was supposed to do.
> 
> Im learning some basics here too and learning a lot from this project. I noticed that they have changed the way they deal with login scene and this "Login Sub Scene 1" is depricated info, for some reason it has been "cached" for "Default Login Scene" itself. I simply went to "Default Login Scene" -> Under "Light etc." in Hierarchy you found "AreaPortal". From there Area Portal script uses Sub Scene value. Set it so some scene and then back to none, rebuild and the warning is gone and compiler not trying to find "Login Sub Scene 1" anymore.
