### ISSUE TITLE
Keep getting tons of MissingMethodException: void UnityEngine.Debug.LogWarning(string, string, int, int)

### ISSUE THREAD

**Issue by aggaton** [wovencode/OpenMMO#74]
I enabled development and debug build and started getting a ton of above errors. Tried to get the the debugger to break at this exception, however there was no stacktrace at all and just stopped me in some Update function. This may ne related to the fact that the character is not moving at all (which is why I enabled debug mode in the first place).

Any idea what could be calling LogWarning with such a weird parameter list?

**Comment by DX4D** [comment]
@aggaton I'm going to need a screenshot or copy/paste of the error, I can't do much without knowing those details.

Also, is this a recent pull from the latest update to the master branch, or a different version?

**Comment by aggaton** [comment]
![image](https://user-images.githubusercontent.com/5942273/133303820-9c62c498-4af7-4dd9-859c-e2217227ebca.png)

Is this what you are looking for?

Yeah it is a pretty recent pull a couple of days ago from the asset store.
I basically just downloaded, imported in new project build and ran, first server then client. As I mentioned, I get a ton of these LogWarning errors and the character model cannot move around.

**Comment by DX4D** [comment]
The asset store version is way outdated, you want to pull the latest version of the master branch from github instead.

https://github.com/wovencode/OpenMMO/

Also, come join the discord channel if you need any help getting things up and running, DM me anytime
https://discord.gg/Cx9hAN4

@aggaton
